repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        files: ^(dpypelines|tests)/

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
        files: ^(dpypelines|tests)/

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
    -   id: ruff
        name: ruff
        entry: poetry run ruff check
        language: system
        types: [python]

-   repo: local
    hooks:
    -   id: git-add-fixed
        name: Add fixed files back to commit
        entry: git add
        language: system
        pass_filenames: true
        stages: [pre-commit]
