repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
    -   id: ruff
        name: Ruff format
        entry: poetry run ruff check --fix
        language: system
        types: [python]

    -   id: ruff
        name: Ruff lint
        entry: poetry run ruff format
        language: system
        types: [python]

-   repo: local
    hooks:
    -   id: git-add-fixed
        name: Add fixed files back to commit
        entry: git add
        language: system
        pass_filenames: true
        stages: [pre-commit]
