[tool.poetry]
name = "dpypelines"
version = "0.2.0"
description = "Data ingest pipelines for ONS Digital Publishing"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
include = ["dpypelines/schemas/**/*.json"]

[tool.poetry.dependencies]
python = "=3.13.*"
dpytools = {git = "https://github.com/ONSdigital/dp-python-tools.git", tag = "v0.10.1" }
pydantic = "^2.11.5"
openpyxl = "^3.1.5"
pymongo = "^4.13.0"
pandas = "^2.2.3"
unidecode = "^1.4.0"
xmltodict = "^0.14.2"
python-dotenv = "^1.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
ruff = "^0.11.11"
pytest-cov = "^6.1.1"
docker = "^7.1.0"
dictdiffer = "^0.9.0"
pre-commit = "^4.2.0"
moto = {extras = ["s3", "secretsmanager", "ses"], version = "^5.1.4"}
pytest-mock = "^3.14.0"
mongomock = "^4.3.0"
responses = "^0.25.7"
pytest-responses = "^0.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
# Exclude patterns (combining from both Black and Ruff)
exclude = [
    "features/",
    "docs/",
    ".md",
    ".zip",
]

[tool.ruff.lint.isort]
case-sensitive = true
force-single-line = false
force-sort-within-sections = true
combine-as-imports = false
known-first-party = ["dpytools", "dpypelines"]

# Keeping lint configuration
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.semantic_release.remote]
type = "github"

[tool.semantic_release.branches]
sandbox = { match = "sandbox", prerelease = true, prerelease_token = "rc" }
other = { match = "staging|production", prerelease = false }

[tool.semantic_release]
tag_format = "v{version}"
version_toml = [
    "pyproject.toml:tool.poetry.version",
]

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"