name: Python Unit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install poetry
        run: pip install poetry

      - name: Install test dependencies
        run: poetry install

      - name: Pytest (make test)
        run: poetry run pytest