name: Build and tag release

on:
  pull_request:
    branches:
      - sandbox
      - staging
      - production
  workflow_dispatch: 

env:
  BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  release:
   # if: startsWith(github.head_ref || github.ref_name, 'release')
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-release-${{ github.ref_name }}
      cancel-in-progress: false
    permissions:
      contents: write
      packages: write
      id-token: write
      checks: write
      statuses: write
      pull-requests: write
    outputs:
      version: ${{ steps.release.outputs.tag }}
      released: ${{ steps.release.outputs.released }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
      - name: Action | Semantic Version Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9.21.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit: "false"
          tag: "false"
          
      - name: Create Pull Request
        id: create_pull_request
        if: steps.release.outputs.released == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: Release ${{ steps.release.outputs.tag }}"
          sign-commits: true
          branch: "release/${{steps.release.outputs.tag}}"
          title: "Release ${{ steps.release.outputs.tag }}"

      - name: Create Release
        id: create_release
        if: steps.release.outputs.released == 'true'
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: "${{ steps.release.outputs.tag }}"
          name: "Release ${{ steps.release.outputs.tag }}"
          bodyFile: "${{ github.workspace }}/CHANGELOG.md"
          draft: false
          prerelease: ${{steps.release.outputs.is_prerelease}}